---
title: "ECP Mountaineering School Archives"
author: "Ray Pomponio"
format:
  html:
    theme: journal
    toc: true
    embed-resources: true
    anchor-sections: true
execute:
  echo: false
  warning: false
---

```{r}
library(data.table)
reps <- fread(file.path("Data/MtnSchoolStairReps.csv"))
```

Convert rep times to vertical pace in meters per hour (MPH):

```{r}
reps[, PaceMPH:=60 * 132 / TimeMins]
reps[, LogPace:=log(PaceMPH)]
hist(reps$PaceMPH)
```

Examine distribution of (log) climbing pace over seasons:

```{r}
boxplot(LogPace ~ EntryYear, data=reps)
```

Examine distribution of pack weights over seasons:

```{r}
boxplot(Weight ~ EntryYear, data=reps)
```

Relationship between pace, weight, week of season, and rep number:

```{r}
pairs(reps[, .(LogPace, Weight, Week, RepNum)], pch=16, cex=0.75)
```

Weight-adjusted pace, by season:

```{r}
fit.pace <- lm(LogPace ~ Weight, data=reps)
reps[, PredLogPace1:=as.numeric(predict(fit.pace, newdata=reps))]
reps[, DiffLogPace1:=LogPace - PredLogPace1]
boxplot(DiffLogPace1 ~ EntryYear, data=reps)
```

**Adjusting for pack weight, students in the 2023-24 cohort were the slowest of any season over the past 10 years**